### ISSUE TITLE
TownCrier on Ropsten not processing requests

### ISSUE THREAD

**Issue by chatch** [bl4ck5un/Town-Crier#49]
I sent a stock quote request (type: 3) to the Ropsten TownCrier contract. 
See here: https://ropsten.etherscan.io/tx/0xc7578f27ee275eb216a5b9335f3f61081e1e69639d26510d0942e15eead32fcf#eventlog

Looking at the RequestInfo event output there it appears the request was processed and well formed.

However I can't it in requests[] when I query the contract and there was no response delivered either ...

Should I expect this contract to be working on Ropsten?  Or maybe there is something wrong with my request?

Thanks.

**Comment by bl4ck5un** [comment]
Hi chatch, right now we are not supporting testnets. You can use the Town Crier on the main chain.
