### ISSUE TITLE
why make attestation with 0x90...... ???

### ISSUE THREAD

**Issue by varvelworld** [bl4ck5un/Town-Crier#53]
https://github.com/bl4ck5un/Town-Crier/blob/60f424114f92563b3df9abaca21a4abcf9d692a7/src/Enclave/ecall_attestation.cpp#L59

why not pub key's hash ???

**Comment by bl4ck5un** [comment]
Hi, in the version you linked to, the public key is hardcoded and already covered by attestation (in the form of address (essentially a hash of the public key)) https://github.com/bl4ck5un/Town-Crier/blob/60f424114f92563b3df9abaca21a4abcf9d692a7/src/Common/Constants.h#L86.

**Comment by varvelworld** [comment]
so what does 0x90... mean ?

**Comment by bl4ck5un** [comment]
That’s just a dummy value.
