### ISSUE TITLE
Flight scrapper API key disabled

### ISSUE THREAD

**Issue by cromak4** [bl4ck5un/Town-Crier#63]
https://github.com/bl4ck5un/Town-Crier/blob/66e8eb85d4fdf4d05a50d78a8f3a9203c4ddd914/src/Enclave/scrapers/flight.cpp#L66

I have disabled this API key on the FlightAware side since it points to my personal account and is billing me.

1. This scraper will not work until this API key is replaced with a new, valid one.
2. This key corresponds to authorization for a paid service and should not be posted publicly (anyone with access can make requests that will be billed to the account owner). This likely means that this demo will have to be disabled.

**Comment by bl4ck5un** [comment]
Hey Kyle, that's definitely the right thing to do. We should not have used your personal account. Were you charged?
