### ISSUE TITLE
SGX-Enter Script Missing Dependencies

### ISSUE THREAD

**Issue by relyt29** [bl4ck5un/Town-Crier#64]
I'm not sure which Docker build script needs to be edited, but it's kind of annoying to have to run the following (+vim, tmux and sudo) every time you boot into the docker instance:

``` bash
apt-get install libjsoncpp-dev libmicrohttpd10 libmicrohttpd-dev libjsonrpccpp-dev
```

(This is dependencies for the fb-login branch for cmake to configure, not sure if this applies to master as well)

**Comment by bl4ck5un** [comment]
Those are specific to fb-login. That branch contains old code depends on those libs. If this is still relevant, could you rebase fb-login on the master? Rebasing should not be too hard. Changs in the master are mainly in untrusted land.
